name: test
on: [push]
jobs:
  'test':
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl: ['5.24', '5.26', '5.28', '5.30', '5.32', '5.34']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{matrix.perl}}
      - run: lsb_release -a
      - name: test-script
        run: ./.github/scripts/test-script.bash
        shell: bash
      
