name: test
on: [push]
jobs:
  'test':
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl: ['5.30', '5.32', '5.34']
        labone:
          ['https://zhinst.com/sites/default/files/download-center/LabOneLinux64-16.12.42529.tar.gz',
          'https://zhinst.com/sites/default/files/download-center/LabOneLinux64-17.12.51058.tar.gz',
          'https://www.zhinst.com/sites/default/files/download-center/LabOneLinux64-18.12.60796.tar.gz',
          'https://zhinst.com/sites/default/files/download-center/LabOneLinux64-19.05.65305.tar.gz',
          'https://www.zhinst.com/sites/default/files/media/release_file/2020-12/LabOneLinux64-20.07.2701.tar.gz',
          'https://nginx.prod.zhinst.ch4.amazee.io/sites/default/files/media/release_file/2021-09/LabOneLinux64-21.08.20515.tar.gz'
          ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{matrix.perl}}
      - run: lsb_release -a
      - name: test-script
        run: ./.github/scripts/test-script.bash
        shell: bash
        env:
          LABONE_VERSION: ${{matrix.labone}}
      
